### PR TITLE
added subsampling scheme for country, new builds for additional regions

### LINKED ISSUE #1: Write builds for other regions
Write builds in `profiles/czbiohub/builds.yaml` for different regions for automated builds:
1. ~~California, US~~ (`california-global`)
2. Minnesota, US
3. New York, US
4. Washington, US
5. Guangdong, China,
6. ~~Hong Kong, Hong Kong~~ (`hong-kong`)
7. Hubei, China
8. Shanghai, China
9. Iceland
10. Italy
11. Japan
12. United Kingdom

### PR DESCRIPTION
**Pull request by phoenixAja**
adding new subsampling/build schemes for additional 11 regions

closes #1

### CODE REVIEW

**Comment by phoenixAja** [comment]
@samlhao and @ttung here's the `CyclicGraphException` error I was talking about during standup. Run `AUGUR_RECURSION_LIMIT=10000 snakemake --debug-dag --profile profiles/czbiohub auspice/ncov_italy.json` to recreate error. I included std. out of snakemake command below.

```
Building DAG of jobs...
candidate job finalize
        wildcards: build_name=italy
candidate job incorporate_travel_history
        wildcards: build_name=italy
candidate job export
        wildcards: build_name=italy
candidate job refine
        wildcards: build_name=italy
candidate job tree
        wildcards: build_name=italy
candidate job combine_samples
        wildcards: build_name=italy
candidate job subsample
        wildcards: build_name=italy, subsample=country
candidate job mask
        wildcards:
candidate job refilter
        wildcards:
candidate job aggregate_alignments
        wildcards:
candidate job partition_sequences
        wildcards:
candidate job filter
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
selected job filter
        wildcards:
selected job partition_sequences
        wildcards:
selected job aggregate_alignments
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
candidate job diagnostic
        wildcards:
candidate job aggregate_alignments
        wildcards:
selected job aggregate_alignments
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
selected job diagnostic
        wildcards:
selected job refilter
        wildcards:
selected job mask
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
candidate job proximity_score
        wildcards: build_name=italy, focus=country
candidate job mask
        wildcards:
selected job mask
        wildcards:
candidate job download
        wildcards:
selected job download
        wildcards:
candidate job subsample
        wildcards: build_name=italy, subsample=country
CyclicGraphException in line 326 of /home/phoenix/code/ncov/rules/builds.smk:
Cyclic dependency on rule subsample.
```

**Comment by phoenixAja** [comment]
@ttung and @samlhao in case you were working on this I fixed it by tweaking the `czb-country` subsampling rule.

**Comment by ttung** [comment]
oh cool.  i just started looking into it.

**Comment by phoenixAja** [comment]
> oh cool. i just started looking into it.

thanks anyways for the help tony!

**Pull request merged**
